;******************************
%windowssystem%;ASYCFILT.DLL
%windowssystem%;COMCAT.DLL
%windowssystem%;Comdlg32.ocx
%windowssystem%;expsrv.dll
%windowssystem%;MFC40.DLL
%windowssystem%;MSCOMCTL.OCX
%windowssystem%;MSFLXGRD.OCX
%windowssystem%;MSJET35.DLL
%windowssystem%;Msjint35.dll
%windowssystem%;msjter35.dll
%windowssystem%;MSRD2X35.DLL
%windowssystem%;MSREPL35.DLL
%windowssystem%;msstdfmt.dll
%windowssystem%;msvbvm60.dll
%windowssystem%;MSVCRT40.DLL
%windowssystem%;MSWINSCK.OCX
%windowssystem%;OLEAUT32.DLL
%windowssystem%;OLEPRO32.DLL
%windowssystem%;STDOLE2.TLB
%windowssystem%;TABCTL32.OCX
%windowssystem%;THREED32.OCX
%windowssystem%;VB5DB.DLL
%windowssystem%;VB6STKIT.DLL
%windowssystem%;vbajet32.dll
%windowssystem%;wshom.ocx
%apppath%;P28V001.exe
%apppath%;P28V100.exe
%apppath%;PrintSts.dll
