VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "stcA46V755B"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Num_Item         As Long
Public Descricao        As String
Public codigo           As String
Public Tab_Cobert       As String
Public Val_IS           As Double
Public PremioInformado  As Boolean
Public VAL_PR           As Double
Public RA_C4            As Integer
Public VAL_IS_RA        As Double
Public Tip_Origem_C4    As Integer



