VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "stcA46V101B"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Descricao        As String
Public codigo           As String
Public Limite           As Double
Public Chave            As String
Public Tab_Cobert       As String
Public Per_Franq        As Double
Public Val_Franq_Min    As Double
Public Val_Franq_Max    As Double
Public CodCobertLim     As String
Public CodGrupoCobert   As String
