VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsA46V401A"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
'Public Enum enum_TipTransmissao
'    enum_TipTransmissao_Transmissao = 1
'    enum_TipTransmissao_Conexao = 2
'    enum_TipTransmissao_Cotacao = 3
'    enum_TipTransmissao_TransmHide = 4
'End Enum
