;*******************************************************************
;*                                                                 *
;*   Controles utilizados nos programas P046O001 e P046O100.       *
;*                                                                 *
;*******************************************************************
;
;   Tipo do usuário: 1 = Yasuda e 2 = Corretor.
;
[USUARIO]
TIPO=1
TIPOHOMOLOG=2
;
;   Identificação do corretor.
;   >>> Quando usuário Yasuda identifica o corretor padrão (OPCIONAL).
;   >>> Quando usuário corretor identifica o usuário do sistema.
;
;[CORRETOR]
;CODIGO=0001601
;NOME=SEGURATEC
;
;   Base de dados - informações:
;   TIPO: 1 = Access, 2 = SQL-Server e 3 = SYMPHOWARE.
;         (*) 3-RO = Symphoware Read Only.
;             3-RW = Symphoware Read Write.
;   >>> DATABASE = identifica base de dados Access.
;   >>> DSN, UID, PWD e DATABASE = identifica base de dados
;                                  SQL-Server ou SYMPHOWARE.
;
;   Base de dados Multi: Access 97.
;
[P00MPED]
TIPO=2
DATABASE=S:\SyasProd\Diversos\P00MPED.MDB
; DATABASE=C:\User_c\Projetos\SyasMulti\P46V100\P00MPED.MDB
;
;   Base de dados Tarifa: Access 97.
;
[P00APOL]
TIPO=2
DATABASE=S:\SyasProd\Diversos\P00APOL.MDB
;DATABASE=C:\User_c\Projetos\SyasMulti\P46V100\P00APOL.MDB
;
;   Base de dados DBCTRDOC: Access 97.
;
[P0044700]
TIPO=1
DATABASE=\\Sp320116pslunas\Soft\SYASPROD\DADOS\P0044700.MDB
;
;   Base de dados P0043000: Access 97.
;
[P0043000]
TIPO=1
DATABASE=\\Sp320116pslunas\Soft\SYASPROD\DADOS\P0043000.MDB
;
;   Base de dados P0043000: Access 97.
;
[P0043100]
TIPO=1
DATABASE=\\Sp320116pslunas\Soft\SYASPROD\DADOS\P0043100.MDB
;
;   Base de dados DBDLLYAS.
;
;
;   Auxílio automático: 1 = Utiliza auxílio e 2 = Não utiliza auxílio.
;


[AUXILIO]
TIPO=2
;
;   Formulários de impressão de proposta.
;	Entre colchetes - nome do formulário.
;	CONFIG = arquivo de configuração.
;	IMAGEM = arquivo de imagem (formulário).
;
[MULTCOT1]
CONFIG=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTCOT1.CXY
IMAGEM=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTCOT1.WMF
[MULTCOT2]
CONFIG=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTCOT2.CXY
IMAGEM=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTCOT2.WMF
[MULTCOT3]
CONFIG=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTCOT3.CXY
IMAGEM=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTCOT3.WMF
[MULTCOTA]
CONFIG=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTCOTA.CXY
IMAGEM=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTCOTA.WMF
[MULTPRO1]
CONFIG=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPRO1.CXY
IMAGEM=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPRO1.WMF
[MULTPRO2]
CONFIG=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPRO2.CXY
IMAGEM=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPRO2.WMF
[MULTPRO3]
CONFIG=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPRO3.CXY
IMAGEM=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPRO3.WMF
[MULTPRO4]
CONFIG=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPRO4.CXY
IMAGEM=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPRO4.WMF
[MULTPROB]
CONFIG=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPROB.CXY
IMAGEM=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPROB.WMF
[MULTPROc]
CONFIG=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPROC.CXY
IMAGEM=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPROC.WMF
[MULTPROD]
CONFIG=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPROD.CXY
IMAGEM=\\Sp320116pslunas\Soft\SyasProd\CXY_WMF\MULTPROD.WMF
[L28V009A]
CONFIG=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\L28V009A.CXY
IMAGEM=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\L28V009A.WMF
[ROUBOCOT1]
CONFIG=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\ROUBOCOT1.CXY
IMAGEM=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\ROUBOCOT1.wmf
[ROUBOCOT2]
CONFIG=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\ROUBOCOT2.CXY
IMAGEM=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\ROUBOCOT2.wmf
[ROUBOCOT3]
CONFIG=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\ROUBOCOT3.CXY
IMAGEM=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\ROUBOCOT3.wmf
[ROUBOCOT4]
CONFIG=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\ROUBOCOT4.CXY
IMAGEM=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\ROUBOCOT4.wmf
[ROUBOCOT5]
CONFIG=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\ROUBOCOT5.CXY
IMAGEM=S:\SyasProd\Gerenciador\Syas_Setup\Atual\SYAS\Formularios\ROUBOCOT5.wmf
;
;
;      Formulários Antigos
;
[MULTCOT1_V0]
NOME=MULTCOT1_V0
[MULTCOT2_V0]
NOME=MULTCOT2_V0
[MULTCOT3_V0]
NOME=MULTCOT3_V0
[MULTPRO1_V0]
NOME=MULTPRO1_V0
[MULTPRO2_V0]
NOME=MULTPRO2_V0
[MULTPRO3_V0]
NOME=MULTPRO3_V0
[MULTPRO4_V0]
NOME=MULTPRO4_V0
[MULTPROB_V0]
NOME=MULTPROB_V0
;
;   Endereco do arquivo de transmissao (remessa).
;
[REMESSA]
ENDERECO=REMESSA\
;
;
;   Endereco do arquivo de transmissao (retorno).
;
[RETORNO]
ENDERECO=RETORNO\

[DBDIVERSOS]
TIPO=2
SERVER=SPX20112CSLUMIX
;SERVER=LPX20102PSLUSQL
DATABASE=Ramosdiversos
;UID=diversos
;PWD=testediv
UID=workflow
PWD=yasworkflow


[DBGED]
TIPO=2
SERVER=SPX20112CSLUMIX
;SERVER=LPX20102PSLUSQL
DATABASE=ged
UID=workflow
PWD=yasworkflow

[PATH_ARQUIVOS]
nOME=T:\T.I\Workgroup\Projetos\Sandra\Formulários SYAS\Layout\
;
;
[IMPRESSORA]
NOME=PDFCREATOR
;
[IMPRESSORAFRENTE]
NOME=PDFCREATOR
;
[IMPRESSORAFRENTEVERSO]
NOME=PDFCREATOR
;
[CAMINHOPI]
PATH=S:\SyasProd\Diversos\proposta\
