;*******************************************************************
;*                                                                 *
;*   Controles utilizados nos programas P028O001 e P028O100.       *
;*                                                                 *
;*******************************************************************
;
;   Tipo do usuário: 1 = Yasuda e 2 = Corretor.
;
[USUARIO]
TIPO=1
;
;   Identificação do corretor.
;   >>> Quando usuário Yasuda identifica o corretor padrão (OPCIONAL).
;   >>> Quando usuário corretor identifica o usuário do sistema.
;
;[CORRETOR]
;CODIGO=0001601
;NOME=SEGURATEC
;
;   Base de dados - informações:
;   TIPO: 1 = Access, 2 = SQL-Server e 3 = SYMPHOWARE.
;         (*) 3-RO = Symphoware Read Only.
;             3-RW = Symphoware Read Write.
;   >>> DATABASE = identifica base de dados Access.
;   >>> DSN, UID, PWD e DATABASE = identifica base de dados
;                                  SQL-Server ou SYMPHOWARE.
;
;   Base de dados DBCTRDOC: Access 97.
;
[P0044700]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0044700.MDB
;
;   Base de dados DBDLLYAS.
;
[P0044800]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0044800.MDB
;
;   Base de dados P0042100 (dados comuns).
;
[P0042100]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0042100.MDB
;
;   Base de dados P0042200 (itens).
;
[P0042200]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0042200.MDB
;
;   Base de dados P0042300 (observação dos itens da proposta).
;
[P0042300]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0042300.MDB
;
;   Base de dados P0042400 (fracionamento).
;
[P0042400]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0042400.MDB
;
;   Base de dados P0042500 (controles do SYAS).
;
[P0042500]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0042500.MDB
;
;   Base de dados P0042600 (coberturas dos itens).
;
[P0042600]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0042600.MDB
;
;   Base de dados P0042700 (descontos dos itens).
;
[P0042700]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0042700.MDB
;
;   Base de dados P0042800 (parcelamento).
;
[P0042800]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0042800.MDB
;
;   Base de dados P0042900 (registro padrão).
;
[P0042900]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0042900.MDB
;
;   Base de dados P0043000 (CEP's).
;
[P0043000]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0043000.MDB
;
;   Base de dados P0043100 (Bancos).
;
[P0043100]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0043100.MDB
;
;   Base de dados P0043200 (Coberturas dos produtos).
;
[P0043200]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0043200.MDB
;
;   Base de dados P0043300 (Descontos dos produtos).
;
[P0043300]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0043300.MDB
;
;   Base de dados P0043400 (Consistências dos produtos).
;
[P0043400]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0043400.MDB
;
;   Base de dados P0043500 (Percentuais de desconto de bônus dos produtos).
;
[P0043500]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0043500.MDB
;
;   Base de dados P0043600 (Valores dos descontos dos produtos).
;
[P0043600]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0043600.MDB
;
;   Base de dados P0043700 (Produtos).
;
[P0043700]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0043700.MDB
;
;   Base de dados P0043800 (Seguradoras).
;
[P0043800]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0043800.MDB
;
;   Base de dados P0043900 (Cadastro de apólices - base de dados redeuzida - para corretores).
;
[P0043900]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0043900.MDB
CARGA=I:\A0000100.TXT
;
;   Base de dados P0044000 (Cadastro de apólices - base de dados completa).
;
[P0044000]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0044000.MDB
CARGA=I:\A0000100.TXT
;
;   Base de dados P0044100 (Descrição das consistências dos produtos).
;
[P0044100]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0044100.MDB
;
;   Base de dados P0044200 (Descrição das coberturas).
;
[P0044200]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0044200.MDB
;
;   Base de dados P0044300 (Descrição dos descontos).
;
[P0044300]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0044300.MDB
;
;   Base de dados P0044400 (Base de parametrização do endosso).
;
[P0044400]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0044400.MDB
;
;   Base de dados P0044500 (Cadastro único das consistências).
;
[P0044500]
TIPO=1
DATABASE=C:\Yasuda\Bancos Access\P0044500.MDB
;
;   Base de Multi-Seguro (Descrição do multi).
;
[P00MULTI]
TIPO=1
;DATABASE=C:\SYASPROD\AUTOMOVEL\P00MULTI.MDB
DATABASE=C:\User_C\tfs\P46V999\MNT - Projeto A5\P00MULTI.MDB
;
;
;   Auxílio automático: 1 = Utiliza auxílio e 2 = Não utiliza auxílio.
;
[AUXILIO]
TIPO=2
;
;   Formulários de impressão de proposta.
;	Entre colchetes - nome do formulário.
;	CONFIG = arquivo de configuração.
;	IMAGEM = arquivo de imagem (formulário).
;
[L28V001A]
CONFIG=C:\User_C\tfs\P46V999\MAIN\L28V001A.CXY
IMAGEM=C:\User_C\tfs\P46V999\MAIN\L28V001A.WMF
[L28V002A]
CONFIG=C:\User_C\tfs\P46V999\MAIN\L28V002A.CXY
IMAGEM=C:\User_C\tfs\P46V999\MAIN\L28V002A.WMF
[L28V002B]
CONFIG=C:\User_C\tfs\P46V999\MAIN\L28V002B.CXY
IMAGEM=C:\User_C\tfs\P46V999\MAIN\L28V002B.WMF
[L28V003A]
CONFIG=C:\User_C\tfs\P46V999\MAIN\L28V003A.CXY
IMAGEM=C:\User_C\tfs\P46V999\MAIN\L28V003A.WMF
[L28V004A]
CONFIG=C:\User_C\tfs\P46V999\MAIN\L28V004A.CXY
IMAGEM=C:\User_C\tfs\P46V999\MAIN\L28V004A.WMF
[L28V005A]
CONFIG=C:\User_C\tfs\P46V999\MAIN\L28V005A.CXY
IMAGEM=C:\User_C\tfs\P46V999\MAIN\L28V005A.WMF
[L28V005B]
CONFIG=C:\User_C\tfs\P46V999\MAIN\L28V005B.CXY
IMAGEM=C:\User_C\tfs\P46V999\MAIN\L28V005B.WMF
[L28V006A]
CONFIG=C:\User_C\tfs\P46V999\MAIN\L28V006A.CXY
IMAGEM=C:\User_C\tfs\P46V999\MAIN\L28V006A.WMF
[L28V007A]
CONFIG=C:\User_C\tfs\P46V999\MAIN\L28V007A.CXY
IMAGEM=C:\User_C\tfs\P46V999\MAIN\L28V007A.WMF
[L28V008A]
CONFIG=C:\User_C\tfs\P46V999\MAIN\L28V008A.CXY
IMAGEM=C:\User_C\tfs\P46V999\MAIN\L28V008A.WMF
[L28V009A]
CONFIG=C:\User_C\tfs\P46V999\MAIN\L28V009A.CXY
IMAGEM=C:\User_C\tfs\P46V999\MAIN\L28V009A.WMF
[PROGRAMAS]
P28V100=C:\User_C\tfs\P46V999\MAIN\P28V100.EXE
;
;   Base de dados SQL-SERVER SYASEMIS.
;
[DBSYASEMIS]
TIPO=2
;SERVER=LPX20102PSLUSQL
;DATABASE=syas_emis
;UID=workflow
;PWD=yasworkflow

SERVER=SPX20112CSLUMIX
DATABASE=syas_emis
UID=syas
PWD=testesyas

;SERVER=SPX20112CSLUMIX
;DATABASE=GED
;UID=workflow1
;PWD=yasworkflow

;SERVER=LPX20102PSLUSQL
;DATABASE=DBSYASEMIS
;UID=DBSYAS
;PWD=DBMARCIA

[DBYAS_ND]
TIPO=2
SERVER=192.168.1.50
DATABASE=YAS_ND
UID=yas
PWD=Fujistu01


;
;
;   Endereco do arquivo de transmissao (remessa).
;
[REMESSA]
ENDERECO=C:\User_C\tfs\P46V999\MAIN\REMESSA\
;
;
;   Endereco do arquivo de transmissao (retorno).
;
[RETORNO]
ENDERECO=C:\User_C\tfs\P46V999\MAIN\RETORNO\
;
;   Endereço do executável do SISCAD
;
[SISCAD]
ENDERECO=C:\User_C\tfs\P46V999\MAIN\P37V000.EXE
;ENDERECO=\\SP320116PSLUNAS\Sistema$\Elib\P37V000.EXE
;
;   Proprietario das tabelas de cotação
;
[PROPRIETARIO TABELA]
PROP=GED.DBO.
;   Endereço do executável do P47V001 (Demais Ramos)
;
[P47V001]
ENDERECO=C:\User_C\tfs\P46V999\MAIN\P47V001.EXE
[REPORT WEBSERVICE]
ENDERECO=http://192.168.1.92:9080/SyasWeb/WebServiceAutoNovo/syasautowebservices.svc
USUARIO=cyber03
SENHA=yasuda